# Default values for cla-backend in a dev environment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: cla_backend_local
  tag: latest
  pullPolicy: IfNotPresent

localPostgres:
  enabled: true

service:
  type: NodePort
  port: 80

# Lists don't deep merge, so this list of envVars overrides anything defined in an earlier values file
envVars:
  - name: DEBUG
    value: "True"
  - name: ALLOW_EMPTY_PASSWORD
    value: "yes"
  - name: LOAD_TEST_DATA
    value: "True"
  - name: BACKEND_ENABLED
    value: "True"
  - name: SQS_REGION
    value: "eu-west-2"
  - name: BOTO_ENDPOINTS
    value: "/hom/app"
  - name: WORKER_APP_CONCURRENCY
    value: 4

worker:
  concurrency: 1
  enabled: true
  url: "redis://broker:6379"
  broker:
    local: true
    image: "redis:5.0.6-alpine3.10"
logLevl: DEBUG
