# Default values for cla-backend in a dev environment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
environment: "uat"
image:
  pullPolicy: IfNotPresent

localPostgres:
  enabled: true

queueWorkers:
  enabled: false

ingress:
  enabled: true
  whitelist_additional:
    - 52.210.85.116/32

# Lists don't deep merge, so this list of envVars overrides anything defined in an earlier values file
envVars:
  DEBUG:
    value: "False"
  DB_PASSWORD:
    value: "thisisapassword"
    secret: ~
  DB_USER:
    value: "postgres"
    secret: ~
  DB_NAME:
    value: "cla_backend"
    secret: ~
  DB_HOST:
    secret:
      optional: true
  DB_PORT:
    secret:
      key: port
      optional: true
  REPLICA_DB_HOST:
    secret:
      optional: true
  LOAD_TEST_DATA:
    value: "True"
  SQS_ACCESS_KEY:
    value: ""
  SQS_SECRET_KEY:
    value: ""
